#!/bin/bash

# TODO check if we need sudo rights
# and fail fast if so

cd ..
DOTS_ROOT=`pwd`

# TODO Check for existing files
# and back them up

symlink() {
    printf "Linking $ROOT/$1 -> $1 ..."
    ln -s $1 $ROOT/$1
    printf "Done!\n"
}

cd $DOTS_ROOT/bash
symlink .bash_profile

cd $DOTS_ROOT/vim
symlink .vimrc



