#!/bin/bash

cd ..
DOTS_ROOT = `pwd`

# TODO Check for existing files
# and back them up

symlink() {
    printf "Linking $1..."
    ln -s $1 $ROOT/$1
    printf "Done!\n"
}

cd $DOTS_ROOT/bash
symlink .bash_profile

cd $DOTS_ROOT/vim
symlink .vimrc



